name: pr lint
on:
  pull_request_target:
    types: [opened, edited, synchronize]
jobs:
  enforce_title:
    name: pr lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Use commitlint to check PR title
        run: echo "${{ github.event.pull_request.title }}" | bun commitlint
