name: unit-tests
on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
jobs:
  unit-tests:
    name: unit-tests
    permissions: write-all
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-unit-tests
      cancel-in-progress: true
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Run the tests
        run: bun run test
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          PIMLICO_API_KEY: ${{ secrets.PIMLICO_API_KEY }}
          PAYMASTER_URL: ${{ secrets.PAYMASTER_URL }}
          BUNDLER_URL: ${{ secrets.BUNDLER_URL }}
          VIRTUAL_BASE_SEPOLIA: ${{ secrets.VIRTUAL_BASE_SEPOLIA }}
          CHAIN_ID: 84532
          ALT_CHAIN_ID: 11155420
          CI: true 
